import type { Metadata, Viewport } from "next";
import { Geist, Fraunces } from "next/font/google";
import "./globals.css";
import { AmbientBackground } from "./components/ambient-background";
import { FAQ } from "./seo-content";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});

const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["400", "500"],
  style: ["normal", "italic"],
  variable: "--font-fraunces",
});

const SITE_URL = "https://alik-ai.com";
const SITE_NAME = "alik";
const TITLE = "alik — AI-curated rooms for real-life connection";
const DESCRIPTION =
  "alik is an AI for real-life connection. you just talk to it; it learns who you are and finds your people (friends, community, a run mate, sometimes love), then its AI talks to theirs to introduce you in real life. no profiles, no swiping. 25+, invite-only.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    template: "%s · alik",
  },
  description: DESCRIPTION,
  applicationName: SITE_NAME,
  generator: "Next.js",
  keywords: [
    "alik",
    "discover alik",
    "AI for real-life connection",
    "AI matchmaker",
    "AI that finds friends",
    "make friends as an adult",
    "meet people without swiping",
    "alternative to dating apps",
    "no swiping no profiles",
    "find your community",
    "find a run mate",
    "meet people 25 and up",
  ],
  authors: [{ name: "alik", url: SITE_URL }],
  creator: "alik",
  publisher: "alik",
  category: "social",
  referrer: "origin-when-cross-origin",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: SITE_URL,
  },
  verification: {
    google: "7HSBXXr_uXXPWc5UdbeR0Zh8PpUA-KnGxFr5WfqP_6o",
  },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: TITLE,
    description: DESCRIPTION,
    locale: "en_US",
    // og:image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    // twitter:image is generated by app/twitter-image.tsx
  },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/alik-icon.svg", type: "image/svg+xml" },
    ],
    apple: [{ url: "/alik-icon.png", sizes: "512x512", type: "image/png" }],
  },
  manifest: "/manifest.webmanifest",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#efe8d7" },
    { media: "(prefers-color-scheme: dark)", color: "#2d3b2e" },
  ],
  width: "device-width",
  initialScale: 1,
  colorScheme: "light",
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${SITE_URL}#organization`,
      name: SITE_NAME,
      url: SITE_URL,
      logo: `${SITE_URL}/alik-icon.png`,
      description: DESCRIPTION,
      slogan: "AI-curated rooms for real-life connection.",
      sameAs: [
        "https://www.instagram.com/discover_alik/",
        "https://www.tiktok.com/@discover_alik",
      ],
    },
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}#website`,
      url: SITE_URL,
      name: SITE_NAME,
      description: DESCRIPTION,
      publisher: { "@id": `${SITE_URL}#organization` },
      inLanguage: "en-US",
    },
    {
      "@type": "Service",
      "@id": `${SITE_URL}#service`,
      name: "alik",
      serviceType: "AI companion and matchmaking for real-life connection",
      description:
        "An AI you talk to that learns who you are, talks to other people's AI, and introduces you to the people who should be in your life: friends, community, a run mate, or love. No profiles or swiping. For adults 25 and up.",
      url: SITE_URL,
      provider: { "@id": `${SITE_URL}#organization` },
      areaServed: "Worldwide",
      audience: {
        "@type": "Audience",
        audienceType: "People seeking genuine real-life connection",
      },
    },
    {
      "@type": "FAQPage",
      "@id": `${SITE_URL}#faq`,
      mainEntity: FAQ.map(({ q, a }) => ({
        "@type": "Question",
        name: q,
        acceptedAnswer: { "@type": "Answer", text: a },
      })),
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geist.variable} ${fraunces.variable} h-full antialiased`}
    >
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="min-h-[100svh] flex flex-col">
        <AmbientBackground />
        {children}
      </body>
    </html>
  );
}
